apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-service
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-service
  template:
    metadata:
      labels:
        app: infra-service
    spec:
      containers:
        - name: infra-service
          image: 858507113889.dkr.ecr.ap-northeast-2.amazonaws.com/argocd/infra-service:latest

          ports:
            - containerPort: 9003 # Spring Boot 앱 포트
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            
            # 1. DB 접속 정보 (keycloak-db 서비스 이름과 포트 5432 일치 확인됨)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://keycloak-db:5432/keycloak"
            - name: SPRING_DATASOURCE_USERNAME
              value: "keycloak"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "keycloak"
            # 2. docker-compose에 있던 초기화 스크립트 대신 JPA가 직접 생성하게 함
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_FLYWAY_CREATE_SCHEMAS
              value: "true"
            # 3. 인증 서버 정보 (이 주소가 틀리면 0초 만에 Crash 발생)
            # - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
            #   value: "http://keycloak-service:8090/realms/ctrlf"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak-service:8090/realms/ctrlf/protocol/openid-connect/certs"
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 9003
          #   initialDelaySeconds: 180
          #   periodSeconds: 10
      nodeSelector:
        zone: private
        