apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-service
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-service
  template:
    metadata:
      labels:
        app: infra-service
    spec:
      containers:
        - name: infra-service
          image: 858507113889.dkr.ecr.ap-northeast-2.amazonaws.com/argocd/infra-service:latest

          ports:
            - containerPort: 9003 # Spring Boot 앱 포트
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_FLYWAY_CREATE_SCHEMAS
              value: "true"
            # DB 접속 정보 (keycloak-db 서비스 이름과 일치해야 함)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://keycloak-db:5432/keycloak"
            - name: SPRING_DATASOURCE_USERNAME
              value: "keycloak"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "keycloak"
            # Keycloak 인증 서버 정보 (keycloak-service 포트 8090 필수)
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak-service:8090/realms/ctrlf"
          livenessProbe:
            httpGet:
              path: /health
              port: 9003
            initialDelaySeconds: 60 
            periodSeconds: 10
      nodeSelector:
        zone: private
        