# 1. Keycloak DB 서비스
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db # [여기] Service가 찾아올 이름
  template:
    metadata:
      labels:
        app: keycloak-db # [여기] Pod에 붙는 이름
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          value: "keycloak"
        - name: POSTGRES_USER
          value: "keycloak"
        - name: POSTGRES_PASSWORD
          value: "keycloak"
---
# 2. Keycloak 서버 서비스
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-keycloak
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak # [여기] Service가 찾아올 이름
  template:
    metadata:
      labels:
        app: keycloak # [여기] Pod에 붙는 이름
    spec:
      containers:
      - name: keycloak
        image: 858507113889.dkr.ecr.ap-northeast-2.amazonaws.com/argocd/keycloak:latest
        ports:
          - containerPort: 8090
        env:
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://keycloak-db:5432/keycloak"
        - name: KC_DB_USERNAME
          value: "postgres"
        - name: KC_DB_PASSWORD
          value: "postgres"
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        # 리소스 제한 (노드 자원이 부족하므로 명시하는 것이 좋습니다)
        # resources:
        #   requests:
        #     memory: "512Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "1024Mi"
        #     cpu: "500m"