spring:
  datasource:
    url: jdbc:postgresql://keycloak-db.argocd.svc.cluster.local:5432/db
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-service:8090/realms/ctrlf
ai:
  gateway:
    url: http://192.168.0.112:8000
